### ISSUE TITLE
Committee Details

### ISSUE THREAD

**Issue by tobytwigger** [bristol-su/committee-portal#1]
Committee Details Status Tracker

**Comment by tobytwigger** [comment]
**TODO**
- [x] Basic scaffolding of a frontent layout.
- [x] Popup implemented with form to create new committee
- [x] Link UnionCloud Account to UnionCloud
- [ ] Position field should get information from the Control Database
- [ ] Implement routes for adding a new member to the database
- [ ] Fill out logic for the above
- [ ] Ensure form can act as an edit or new resource form i.e. old values are populated
- [ ] Implement 'submit' button to upload to Control Database
- [ ] Control access to the module
- [ ] Listen for event from the initial president module
- [ ] Make sure edit and delete buttons are only present when necessary
- [ ] Setup middleware to provide registration with a Control ID

**Comment by tobytwigger** [comment]
Vue JS is a much smarter solution for the searching of a unioncloud account, since it allows for automating DOM getter and setters.

This has been partially implemented (see db4a79b), but still needs more work.
